### PR TITLE
Adding Python 3 Compatibility 

### PR DESCRIPTION
**Pull request by JasonKessler**
Some others may have beat me to this, but the changes in this PR make this code Python 3 compatible.

### CODE REVIEW

**Comment by adamhadani** [comment]
+1 bump

**Comment by AbeHandler** [comment]
@JasonKessler Thanks for your help.

**Comment by JasonKessler** [comment]
Happy to help!

**Comment by AbeHandler** [comment]
Cool. `$pip install -U phrasemachine` should update to version 1.0.4 w/ your changes. If you see any issues after the upgrade definitely let me know!

**Pull request merged**
